// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Revalb.Data;

#nullable disable

namespace Revalb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250515120820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Revalb.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<string>("ArtistIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverSlika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArtist")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProsjecnaOcjena")
                        .HasColumnType("real");

                    b.PrimitiveCollection<string>("Zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlbum");

                    b.ToTable("Albumi", (string)null);
                });

            modelBuilder.Entity("Revalb.Models.Korisnik", b =>
                {
                    b.Property<int>("idKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idKorisnik"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nadimak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("brojRecenzija")
                        .HasColumnType("int");

                    b.HasKey("idKorisnik");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("Revalb.Models.Pjesma", b =>
                {
                    b.Property<int>("idPjesma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPjesma"));

                    b.Property<int>("Trajanje")
                        .HasColumnType("int");

                    b.Property<string>("fajl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idAlbum")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("redniBroj")
                        .HasColumnType("int");

                    b.HasKey("idPjesma");

                    b.ToTable("Pjesme", (string)null);
                });

            modelBuilder.Entity("Revalb.Models.Recenzija", b =>
                {
                    b.Property<int>("idRecenzija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecenzija"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zvjezdice")
                        .HasColumnType("int");

                    b.Property<int>("idAlbum")
                        .HasColumnType("int");

                    b.Property<int>("idRecenzent")
                        .HasColumnType("int");

                    b.HasKey("idRecenzija");

                    b.ToTable("Recenzije", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
